-- First experiment --CREATE TABLE public.experimenting(
-- First experiment   experimenting_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
-- First experiment   experimenting_name CHARACTER VARYING NOT NULL,
-- First experiment   experimenting_class character varying NOT NULL
-- First experiment );
-- First experiment 
-- First experiment SELECT * FROM public.experimenting
-- First experiment ORDER BY experimenting_id ASC 

--TASK 1 

--1
INSERT INTO public.account 
    (account_firstname, account_lastname, account_email, account_password )
	VALUES 
	('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n')

--2
UPDATE account 
   SET account_type = 'Admin'

--3
DELETE FROM account 
  WHERE account_id = 1 

--4
UPDATE public.inventory
   SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
   WHERE inv_id = 10 ;

--5
SELECT inv.inv_make, inv.inv_model,
        class.classification_name
FROM public.inventory inv
INNER JOIN public.classification class
    ON inv.classification_id = class.classification_id
WHERE class.classification_name = 'Sport';  

--6
UPDATE public.inventory
   SET inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/'),
       inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/')